sudo: required
dist: trusty
env:
  global:
    - CODECLIMATE_REPO_TOKEN=$CC_TEST_REPORTER_ID
    - CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN
addons:
  apt:
    # update: true
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - stable
before_install:
  - npm i -g npm
  - npm i -g codecov
  - npm i -g codeclimate-test-reporter
  - npm i -g codacy-coverage
  - npm i -g live-server@1
  - npm i -g node-gyp@3
  - cd src/ngx-smart-modal
install:
  - npm install
script:
  - npm run test
  - npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - codecov -t $CODECOV_TOKEN
  - codeclimate-test-reporter < 'coverage/lcov.info'
  - cat coverage/lcov.info | codacy-coverage
  - rm -r node_modules
  - cd ../..
  - npm run ghpages
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $PUSH_TOKEN
  on:
    branch: master
